import logging
import multiprocessing
import os
import random
from random import shuffle
import sys
import traceback
from concurrent import futures
from concurrent.futures import ThreadPoolExecutor
from threading import Thread

from flask import Flask, request, jsonify, render_template

from Class.site import Site
from Database.atlas import MongoAtlas, evaluate_site, get_site_to_evaluate, add_site
from Frontpages.evaluate import open_site
from Google.google_function import get_ads_data_test, get_myips_link, get_trend
from Google.google_function import get_facebook_data
from Google.google_function import get_store_products
from Google.google_function import scrape_my_ips
from Google.google_sheets import GoogleSheets
# from ScaleTest.requests_scale_test import run_test
from Google.google_trends_api import GoogleTrendsApi
from Scrappers.Stats.awis_api_wrapper import get_rank

global main_thread

words = [
"stomp rocket",
"rocket launchers for kids",
"model rocket kits with launch set",
"rocket copters",
"model rocket",
"estes rocket",
"water rocket",
"rockets",
"stomp rockets for kids",
"estes rocket engines",
"model rocket engines",
"rocket launcher",
"model rockets",
"astronaut toys",
"estes",
"rocket kit",
"bottle rocket",
"water rockets for kids",
"rocket toy",
"rockets for kids to launch",
"estes rocket launch kit",
"rocket engine",
"rocket copters with led lights",
"the rocket",
"estes rockets",
"water rocket launcher",
"toy rocket",
"rocket copter",
"kids rocket launcher toy",
"rocket ship",
"toy rocket launcher for kids",
"rockets for adults",
"stomp rockets",
"model rocket kit",
"water rockets",
"model rockets kits for adults",
"rocket launchers",
"rocket kits",
"launcher",
"rocket engines",
"model rocket kits",
"toy rocket ship",
"rocket ship toy",
"rocket kits with launch set and engine",
"rocket launchers for adults",
"bottle rocket launcher",
"water launcher",
"rocket model",
"rockets for kids",
"bottle rockets fireworks",
"bottle rocket kit",
"kids rocket",
"model rocket igniters",
"toy rocket launcher",
"rocket toys",
"nerf rocket",
"water bottle rocket",
"stomp rocket stunt planes",
"air rocket launcher kids",
"rocketship",
"rocket raccoon gun",
"model rocket launch pad",
"boys outdoor toys",
"rocket motor",
"bottle rockets",
"model rockets kits for kids",
"rocket ship toys",
"estes launch pad",
"rocket models",
"air rocket",
"water bottle rocket launcher",
"rocket science",
"rocket copters for kids",
"jump rocket",
"stomp rockets for kids age 4",
"rocket kit for kids",
"rocketcopters",
"toy rockets",
"rocket kits with launch set",
"build your own rocket kit",
"rocket launch kit",
"rc rocket",
"rocet",
"marky sparky blast pad rocket launcher",
"firework launch controller",
"rocket launch",
"estes model rocket",
"slingshot rockets for kids light up",
"space rocket",
"rocket for kids",
"jump rocket launcher for kids",
"4m water rocket kit",
"water powered rocket",
"smithsonian rocket science kit",
"stomp rockets for kids age 6",
"rocket bottle",
"pop rocket",
"rocket igniters",
"baking soda rocket",
"glow rocket",
"estes rocket parachutes",
"rocket bottle launcher",
"ncredible rocket copters",
"model rocket kits with launch set and engine",
"ginormous rocket",
"pump rocket launchers for kids",
"replacement stomp rockets",
"step on rocket launcher",
"stompers",
"on the launch pad",
"rocket launcher for kids",
"rocket copter as seen on tv",
"broyhill estes park",
"hydro stomp splash rocket",
"roket launch",
"apollo rocket toy",
"air launcher toy",
"remote control rocket",
"model rocket kits for adults",
"estes alpha rocket bulk pack pack of 12",
"rocket kits for adults",
"jump and launch",
"bottle launcher",
"geospace jump rocket",
"water launch pad",
"estes este4564",
"stomp rockets for kids junior",
"rockete",
"launch rockets for kids",
"launching rockets",
"rocket lancher",
"toy rockets that launch",
"kid rockets",
"rocket kids",
"rockets for kids to launch outside",
"rocket rocker",
"rocket lonchers",
"kids rocket launcher",
"launch rocket",
"kid rocket launcher",
"rockets to launch",
"rocket kids toy",
"water rocket kits with launch set",
"launching rockets for kids",
"outside rockets",
"toy rockets for boys",
"rocket launcher for boys",
"kid rocket",
"real rocket launcher",
"water rocket kit",
"rocket toy for kids",
"rocket launcher for adults",
"rocket kid",
"kids rocket toy",
"air pump rocket launcher kids",
"toy rocket launchers",
"rocket launcher toy",
"outside rocket",
"step powered rocket",
"rocket salad",
"rocket launcher kit",
"air rockets for kids",
"rocket stomper for kids",
"water rockets for adults",
"outdoor rocket",
"stop rocket",
"rocket toys for kids",
"soda rocket launcher kit",
"backyard rocket",
"rocket launcher for 3 year old",
"jump rocket launcher",
"rockets for boys",
"rocket ship model",
"rocket ship kit",
"outdoor rocket launcher",
"sky rockets for kids",
"kids rocket kit",
"build a rocket kit for kids",
"build rockets for kids",
"rocket toys for boys 8 12",
"kids toy rocket",
"sky rocket",
"jump rockets for kids",
"kid rocket kit",
"rocket blaster for kids",
"step rocket for kids",
"rocket sets with launcher",
"stomp rocket rockets",
"jump rockets",
"stomp rockets dueling rockets",
"water rocket launchers for kids",
"large rocket kit",
"rocket kits with launch set kids",
"water powered rockets for kids",
"rocket boy",
"step rocket",
"stomp rocket toy",
"storm rocket for kids",
"outdoor rockets for kids",
"pump rockets for kids",
"air powered rocket",
"rocket launcher prop",
"outdoor rockets for adults",
"rocket kits for kids",
"rocket set",
"kids stomp rocket",
"launch toy",
"stomp rocket dueling rockets",
"kids water rocket",
"step on rocket launcher toy",
"model rockets for kids",
"toy launcher",
"stomp rocket for 3 year old",
"rocket building kit",
"the water rocket",
"air rockets",
"rocket shooters for kids",
"build the rocket",
"launcher toys for kids",
"build your own rocket kit for kids",
"boy toy rocket",
"step rocket launcher",
"usb rocket launcher",
"rocket games for kids",
"rockets for adults to launch",
"stomping rocket toy",
"rocket science kit",
"build rocket kits with launch set",
"rocket water",
"water rockets with pump",
"original stomp rocket",
"rocket ship toys for boys",
"dog",
"dog collar",
"dog food",
"dog accessories",
"dog stuff",
"dogs",
"dog dna test",
"dog supplies",
"pill pockets for dogs",
"dog training",
"dog grooming",
"collar",
"e collars for dogs",
"pet supplies",
"heartgard for dogs",
"pet supplies for dogs",
"puppy supplies",
"dog dna",
"dog car",
"puppy training",
"pet car seat",
"puppy accessories",
"dog accessories for small dogs",
"pet grooming",
"pet food",
"dog things",
"grooming",
"dogs for sale",
"dog accessories for large dogs",
"dog supplies for medium dogs",
"dog items",
"dogfood",
"dog grooming tools",
"dog pack",
"small dog",
"dog hair",
"comida para perros",
"pitbull toys",
"heart guard dogs",
"accesorios para perros",
"thick dog collar",
"husky dog accessories",
"dog supplies for large dogs clearance",
"real dog",
"collar para perros",
"pet accessories for dogs",
"dog essentials",
"must have cat items",
"the stuff for dogs",
"puppy starter kit",
"dogs stuff",
"dog gadgets",
"collars for dogs",
"mascotas",
"stuff for dogs",
"small dog accessories",
"dog products",
"dog supplies for small dogs clearance",
"pet dog",
"dogs collar",
"puppy starter kit for small dogs",
"puppy essentials",
"tick collar for large dogs",
"pet stuff",
"large dog",
"real dogs",
"things for dogs",
"perros",
"puppy gifts",
"perros accesorios",
"dog supplies puppies",
"dogs accessories",
"pet accessories",
"german shepherd collar",
"pet supplies for cats",
"puppy essentials for small dogs",
"dog supply",
"puppy things",
"dog training tools",
"heartgard plus",
"cool dog stuff",
"puppy dog collar",
"puppy items",
"collar dog",
"dog towels for small dogs",
"pet meds",
"must have dog items",
"cages for small animals",
"mascotas accesorios perros",
"dog den",
"puppy supplies for medium dogs",
"accessories for dogs",
"pet supplies for puppys",
"seat pets",
"local pet store",
"large dog run",
"dag",
"puppy starter kit for medium dogs",
"collar de perro",
"dogs food",
"best dog collars",
"small dogs",
"puppy supplies for large dogs",
"dogs supplies",
"small dog stuff",
"dog pet",
"pet care",
"seatpets",
"training dog",
"dog stuff for small dogs",
"dog foods",
"puppy essential",
"dog collar xl",
"big dog collars for large dogs",
"same for dogs",
"dental dog food",
"dog lot",
"dog supplies for small dogs",
"fish health supplies",
"beach dog accessories",
"paw safe",
"dogs and cats",
"pet training clicker",
"dog collar wide",
"dog carseats",
"big dog",
"pet training",
"pet labs",
"german shepherd accessories",
"dog supplies for large dogs",
"dogs accessories for small dogs",
"small dog supplies",
"big dog collars",
"real puppys for sale",
"dog knows best",
"puppy grooming",
"small animal grooming supplies",
"doog",
"dog collar extra large",
"collar perro",
"cat essentials kit",
"pet essentials for dogs",
"tiny puppy toys",
"real food",
"outdoor dog supply",
"petcare",
"working dog collar",
"heartguard for dogs",
"huge dog toy",
"dog collar large dogs",
"cats & dogs",
"new puppy essentials",
"wide dog collars",
"puppy must have items",
"electric dog toy",
"gifts for dog",
"pet pet",
"dog charger accesory",
"husky collar",
"dog charger cover",
"pet kennels for small dogs",
"puppy supplies for small dogs",
"amazon dog bags",
"waterproof leash for dogs",
"dog stuff pet care",
"dog collar 2 pack",
"heart worm medication for dog",
"water proof dog collars for large dogs",
"great dane supplies",
"professional dog grooming supplies",
"cheap dog stuff",
"good pet stuff",
"dog in training",
"dog heartworm medicine chewable",
"german products",
"flea toy for dogs",
"big and small",
"bog fog",
"treat him like a dog",
"new dog kit",
"pet supply",
"ultimate red paw",
"puppy training tools",
"honest to dog",
"ball retriever for water",
"small dog pack",
"pets stuff",
"pet gadgets",
"think thin bites",
"pet care products for dogs",
"grooming dog",
"pets accessories dogs",
"blyss pets",
"small pets and company",
"water dog collar",
"dogs that look real",
"patriot pup",
"training dogs",
"dog supply storage",
"isle of dogs gift set",
"paw guard for dogs",
"prodent plus for dogs",
"kitten grooming kit",
"pet supplies in prime day",
"collors dogs",
"come and get it dog food",
"small breed dog collar",
"dog collar large dog",
"lab dog",
"storage for dog supplies",
"dog not gone",
"paw care for dogs",
"dog supplies pet stuff",
"puppy essentials for big dogs",
"vet guard for dogs",
"petworld premium",
"a real dog",
"dark dog",
"supplies for dogs",
"s cane",
"large collar",
"dog collar extra large breed",
"bark remote control",
"stop shedding dog",
"dog house accessories",
"pet deals",
"ruff stand",
"heartgard dogs",
"fresh n up",
"bark training",
"embark pets",
"treat pod dog toy",
"beach dog supplies",
"now dog",
"puppy training set",
"pitbull supplies",
"dog smell proof",
"pill dog treats",
"pawtree dog food",
"collor",
"puppy training treats for medium dogs",
"dog an",
"puppy supplies for labs",
"pitbull lab mix",
"pet supplies deals",
"dog clearance",
"big dogs",
"bulk dog",
"best dog",
"mask",
"face mask",
"face masks",
"n95 mask",
"kids face mask",
"cloth face mask",
"masks for germ protection",
"cloth face mask washable",
"n95 masks for sale",
"n95",
"black mask",
"reusable masks",
"kn95",
"medical face mask",
"disposable mask",
"3m n95 mask",
"mascarillas antivirus",
"cloth masks",
"kn95 face mask",
"black face mask",
"masks for germ protection n95",
"reusable face mask",
"surgical masks disposable",
"medical mask",
"facemask",
"dust mask",
"reusable mask",
"n95 masks",
"n95 respirator mask reusable",
"bandana mask",
"surgical mask",
"washable face masks for germs",
"filter mask",
"disposable masks",
"bandanas for men",
"kn95 mask",
"reusable face masks",
"mask with filters",
"cloth mask",
"cloth masks for nose and mouth washable",
"n95 face mask",
"surgical masks",
"masks made in usa",
"cotton face mask",
"kids masks",
"washable face mask",
"mascarillas",
"medical face masks for virus protection",
"kids surgical mask",
"breathable face masks",
"facial mask",
"face masks medical",
"mask for kids",
"facemasks",
"surgical masks disposable made in usa",
"breathable face mask",
"cloth face mask washable prime",
"cute masks",
"cloth face masks",
"vogmask",
"cotton face masks",
"cubre bocas",
"adjustable face mask",
"mascarillas antivirus n95",
"masks with filter",
"mask n95",
"cute face mask",
"scarf face mask",
"bandana face mask",
"mask with filter",
"cotton mask",
"kids face masks",
"n 95 facemasks medical",
"n95 mask reusable",
"black masks",
"n95 mask 3m",
"washable masks",
"carbon filter face mask",
"cute face mask washable",
"kids disposable face mask",
"kn95 respirator mask",
"masks for coronavirus protection made in usa",
"n95 masks for virus protection made in usa",
"k95 face masks",
"black face mask washable",
"n95 mask medical",
"medical masks",
"mouth mask",
"washable face masks",
"kn95 masks",
"black masks for germ protection",
"black surgical mask",
"masks for germ protection made in usa",
"childrens face mask",
"paper masks",
"large face mask for men",
"masks n95",
"running breathing mask",
"white face mask",
"face mask for men",
"face",
"cotton face mask washable",
"designer face mask for women",
"curad antiviral mask",
"m95 face masks",
"3m face mask",
"cotton masks for face washable",
"cotton masks",
"polyester face mask",
"level 3 masks",
"black disposable face mask",
"black face mask with filter",
"breathable mask",
"child face mask",
"face mask bandana",
"mens face mask",
"n 95 mask",
"surgical face mask",
"cute surgical mask",
"reusable masks with filter",
"kn95 masks for sale",
"kids face mask with filter",
"black face masks",
"womens face mask",
"masks for women",
"mascarilla",
"ppe face mask",
"adult face masks",
"kid face mask",
"antibacterial mask",
"n95 face masks",
"breathable face mask with filter",
"children face mask",
"mask reusable",
"cloth face mask washable with filters",
"masks for sale",
"cotton face mask washable made in usa",
"child mask",
"washable face mask with filter",
"mascarillas de tela para la boca",
"cycling mask",
"white mask",
"masks reusable",
"antiviral mask",
"childrens face mask reusable",
"3m masks",
"dust masks",
"boomer naturals face mask",
"black face mask reusable",
"black mask with filter",
"baby face mask",
"washable mask",
"3 layer face mask",
"usa face mask",
"antivirus mask",
"large face mask",
"womens face mask reusable",
"protective face masks",
"cubrebocas",
"n95 masks for sale for virus",
"mask for virus protection made in usa",
"paper masks for virus protection",
"black surgical face mask",
"cubre bocas desechables",
"mask for women",
"mask for men",
"breathable masks",
"made in usa face mask",
"masks for men",
"face madk",
"black disposable mask",
"mask black",
"n 95",
"3m n95 mask medical",
"medical face masks",
"k95 mask",
"white masks",
"3 ply face mask",
"mascarillas n95",
"mens mask",
"pink disposable face mask",
"adjustable face mask reusable",
"lightweight face mask",
"lace face mask",
"reuseable face mask washable",
"masks washable",
"white face mask washable",
"children mask",
"cloth face masks washable",
"reuseable mask",
"mascarillas desechables",
"mask kids",
"kids face mask n95",
"halyard mask",
"medical grade face mask for virus protection",
"madk",
"black cloth face mask washable",
"cloth face mask with filter",
"beatbasic",
"pediatric face mask",
"disposable masks made in usa",
"adult face mask",
"cubre bocas de tela",
"women face masks",
"mask made in usa",
"masks made in usa only",
"face maks",
"byd face mask",
"mask face",
"thin face mask",
"kf94 mask korea",
"fave mask",
"small face mask",
"maks",
"best face mask",
"modenna",
"mask kn95",
"mascarilla n95",
"construction mask",
"tapabocas antivirus",
"black n95 mask",
"black face mask disposable",
"n95 mask with filter",
"cloth face mask washable made in usa",
"covid masks for germ protection",
"paper face masks",
"paper mask",
"madks",
"n 95 masks",
"masks black",
"mouth covers",
"kn 95 maks",
"dental mask",
"no fog face mask",
"n95 masks for sale 3m",
"masks with designs",
"reusable face mask with filter",
"kids face mask disposable",
"surgical face masks",
"childrens masks",
"blue mask",
"cute face masks reusable",
"red face mask",
"mask with nose wire",
"cloth face masks made in usa",
"95 masks",
"disposable mask black",
"organic cotton face mask",
"masks cloth",
"surgical masks made in usa",
"card",
"steam gift card",
"vbucks gift card",
"fortnite vbucks",
"vbucks",
"cards",
"steam",
"v bucks",
"v bucks gift card",
"steam card",
"robux gift card",
"steam gift card digital code",
"nintendo gift card",
"vbucks gift card digital code",
"minecraft gift card",
"enail",
"steam gift card email delivery",
"play store gift card",
"small gifts",
"google gift card",
"digital gift cards",
"steam wallet gift card email delivery",
"apple gift card 10",
"last order",
"10 gift card",
"cheap gifts",
"steam digital code",
"redeem gift cards",
"digital code",
"digital gift card",
"gift card balance how to check",
"gift cards fathers day",
"25 gift card",
"food delivery",
"bulk gifts",
"xbox giftcard",
"steam card digital code",
"vbucks gift card 10",
"5 dollar gift cards",
"same day delivery",
"itunes gift card 10",
"delivery box",
"grubhub gift card email delivery",
"play staystion 4 gift card",
"the last of us merchandise",
"steam wallet",
"steam giftcard",
"add gift card to my account",
"birthday delivery gifts",
"steam gift card 10",
"10 itunes gift card",
"25 dollar gift card",
"google play card 10 dollars",
"steam code",
"steam card email delivery",
"google play gift cards",
"50 dollar gift card",
"target stores online shopping",
"roblox cards",
"vbucks digital code",
"apple card digital code",
"pizza hut",
"redeem code",
"playstore giftcard",
"steam gift",
"10 vbucks gift card",
"noto",
"100 dollar gift card",
"redeem gift cards for amazon to my account",
"10 apple gift card",
"best gifts",
"steam cards",
"x box gift card",
"5 dollar gift card",
"gift card roblox",
"valorant gift card",
"steam digital gift card",
"roblox giftcard",
"20 gift card",
"buy again",
"small gift",
"roblox gift",
"big idea design",
"amazon orders",
"xbox gift card digital code 20",
"check balance on amazon gift card",
"shop amazon com",
"xbox gift card 25",
"gift cards xbox",
"vbucks gift card 25",
"pay pal",
"gift card digital code",
"xbox roblox",
"20 dollar gift card",
"return items purchased",
"v bucks gift card digital code",
"roblox gifts",
"gift card fortnite",
"returns for items purchased from amazon",
"youtube gift cards",
"gift card boxes",
"roblox premium gift card",
"itune",
"return gifts",
"apple gift",
"sephora e gift card",
"your orders on amazon",
"30 xbox gift card digital code",
"10 google play card",
"vbuck card",
"the one with all the cards",
"vbox gift card",
"steam gift card 25",
"10 dollar apple gift card",
"amazon electronics",
"spotify gift card 1 year",
"redeem amazon gift card code to your account",
"prime day phone deals",
"steam wallet codes",
"25 dollars",
"oculus gift card",
"delivery",
"steam gift card 20",
"make electronics",
"online stores",
"roblox gift card 50",
"20 dollars",
"no thanks",
"steam gift card 50",
"psn card digital code 50",
"5 dollar itunes gift card",
"25 vbucks gift card",
"xbox gift card 50",
"redeem code ps4",
"vbuck gift card",
"5 dollar xbox gift card digital code",
"roblox gift card 100 dollars",
"5 gift card",
"ps4 gift card digital code 25",
"tarjeta",
"add gift card balance",
"prepaid",
"15 dollar gift card",
"25 dollar roblox gift card",
"take a number",
"vouchers",
"apple cards",
"gift card steam",
"sent away",
"gift cards roblox",
"bulk cards",
"steam wallet card",
"30 dollar ps4 gift card",
"amazon balance",
"roblox gift card digital code 25",
"going away card",
"gif cars ps4",
"pack of cards",
"steam gift card digital",
"minecraft prepaid card",
"quicklot",
"psn card digital code 25",
"roblox gift card 50 dollars",
"gifs for fathers day",
"10 dollar ps4 card digital code",
"play card",
"5 dollar apple gift card",
"the last of us digital code",
"pay phone",
"tarjetas de roblox",
"1 hour delivery",
"tarjeta ps4",
"vbucks gift card fortnite",
"roblox gift card 25 dollars",
"return orders from amazon",
"20 steam gift card",
"ps4 gift card digital code 40",
"load gift card to my account",
"best gift",
"xbox gift card digital code 15",
"gift cards for xbox",
"birthday ecard",
"itunes gift card digital code 10 dollars",
"steam wallet gift card code",
"google play card email delivery 10",
"tarjetas de ps4 store",
"5 apple gift card digital code",
"digital card",
"quick lot",
"same day delivery gift",
"tarjeta play store",
"gift code",
"gift card wallet",
"email address",
"xbxo giftcard",
"100 dollar roblox gift card",
"restaurants order food delivery",
"gifts under 50 dollars",
"10 xbox card",
"steam e gift card",
"steam 10 dollar gift card",
"100 dollar",
"20 dollar",
"how to redeem amazon gift card",
"under 100 dollar items",
"gift card xbox one digital code",
"gif for fathers day",
"southwest gift",
"gifs",
"roblox ecard",
"10 steam gift card",
"vbuck cards",
"paypal gift card digital code",
"steam 20 gift card digital code",
"roblox gift card 15",
"10 dollar xbox gift card digital code",
"steam card 20 dollar",
"10 gift card ps4",
"steam wallet code",
"100 vbucks gift card",
"code 50",
"gift cards for roblox",
"steam gift card 100",
"gift cards ps4 digital code",
"gifts under 60 dollars",
"gift card redeem to my account",
"gift pack",
"ps4 50 gift card digital code",
"20 dollar roblox gift card",
"xbix 25 gift card",
"steam gift card code",
"ps4 10 dollar gift card",
"25 google play card",
"great clips gift cards",
"25 dollar",
"roblox gift card email delivery",
"birthday delivery",
"xbox gift card digital code 10 dollars",
"wallet",
"wallets for men",
"wallets for women",
"mens wallet",
"ridge wallets for men",
"wallets",
"womens wallets",
"men wallet",
"ridge wallet",
"slim wallets for men",
"wallet for men",
"wallet for women",
"minimalist wallets",
"womens wallet",
"slim wallet",
"small wallets for women",
"thread wallets",
"mens wallets",
"wallets for women clearance",
"leather wallets for men",
"women wallet",
"carteras para hombres",
"minimalist wallet",
"the ridge wallet",
"carbon fiber wallet",
"billeteras de hombres",
"gucci wallet for men",
"trifold wallets for men",
"leather wallet",
"rfid wallets for men",
"card wallet",
"small wallet",
"gucci wallet",
"mens wallets trifold leather",
"herschel wallet",
"fossil wallet men",
"nike wallet",
"mens slim wallet",
"mens leather wallet",
"rfid wallet",
"walett for men",
"minimalist wallet for men",
"wallets for boys",
"wallets for men minimalist",
"wallet women",
"front pocket wallet",
"personalized wallets for men",
"money clip wallet",
"men wallets",
"thin wallet",
"metal wallets for men",
"leather wallet for successful men by dimostyle",
"mens wallets bifold leather",
"trayvax wallet",
"smart wallets for men",
"credit card wallet",
"tactical wallets for men",
"card wallet for men",
"carbon fiber wallets for men",
"tommy hilfiger wallet",
"mens wallet leather for successful men by dimostyle",
"tactical wallet",
"boys wallet",
"bifold wallets",
"wallet men",
"smart wallet",
"tommy hilfiger wallets for men",
"mens wallets slim for successful men by dimostyle",
"touch carbon slim wallet",
"mens trifold wallet",
"trifold wallet",
"mens wallet with money clip inside",
"fossil wallet",
"small womens wallet",
"carhartt wallet for men",
"leather wallet for men by dimostyle",
"cartera de hombre",
"mens wallet black",
"women wallets",
"bifold wallet",
"the ridge wallets for men",
"bifold wallet men",
"designer wallets for men",
"black wallet",
"rfid",
"small wallets for men",
"small wallet for women",
"carteras",
"leather wallets",
"men wallet leather",
"womans wallet",
"edc wallet",
"photo wallet",
"dad wallet",
"michael kors wallet men",
"tactical wallets",
"clip wallet for men",
"wallets for women small",
"wallets for men personalized",
"slim wallets",
"cool wallets for men",
"men wallets on sale clearance prime",
"small wallets",
"cool wallets",
"mens wallet with zipper",
"thin wallets",
"walet",
"mini wallet",
"nike wallets for men",
"rfid blocking wallet",
"timberland wallets for men",
"personalized wallet",
"minimalist wallets for men",
"wallet minimalist",
"slim mens wallet",
"guess wallet for men",
"id wallet",
"calvin klein wallets for men",
"thin wallets for women",
"magic wallet",
"timberland wallet",
"coach wallets for men",
"rigid wallets for men",
"andar wallets for men",
"mens wallet slim",
"compact wallet",
"cartera",
"mens leather wallets",
"polo wallets for men",
"wallet clip for men",
"carhartt wallet",
"womens small wallet",
"slim wallet for men",
"vans wallet",
"mens wallet bifold",
"hershel wallet mens",
"thin wallets for men",
"titanium wallet",
"mens leather wallet bifold slim",
"mens wallets leather",
"zipper wallets for men",
"fantom wallet",
"mens wallet leather",
"cool wallet",
"ridge wallets",
"minimal wallet",
"columbia wallets for men",
"wallet slim",
"travando money clip wallet",
"credit card wallet for men",
"touch carbon wallet",
"demon wallet",
"man wallet leather",
"men leather wallet",
"leather wallet for men",
"women wallets clearance",
"woman wallets",
"wallet card",
"shype wallet for men",
"touchcarbon slim wallet",
"smart wallets",
"mens front pocket wallet",
"volterman smart wallet",
"black leather wallet",
"calvin klein wallet",
"wallets for fathers day",
"man wallet",
"mens wallet minimalist",
"card wallets",
"mens bifold wallets leather",
"gucci mens wallet",
"tommy hilfiger men wallet",
"trifold leather wallets for men",
"large wallets for women",
"card holder wallet for men",
"wallet for boys",
"photo wallet for men",
"wallet mens",
"tri fold wallet",
"wallets for men rfid blocking",
"bifold wallets for men",
"wallets for men slim",
"woman wallet",
"black wallet for men",
"rfid wallets",
"billeteras de hombres personalizadas",
"pocket wallet",
"ridge wallets for men carbon fiber",
"mens wallet with money clip",
"slim metal wallet",
"rfid wallet for men",
"card wallet men",
"best wallets for men",
"wallet money clip",
"mens bifold wallet",
"men wallet with zipper",
"flat wallet",
"pocket wallet for men",
"fossil wallets for men",
"wallets for men trifold",
"compact wallet for men",
"designer wallet",
"walets",
"modern wallet",
"wallets for teens",
"mens coach wallets",
"thin wallets for men leather",
"wallet for dad",
"gucci wallets for men",
"rfid blocking wallets for men",
"edc wallets for men",
"tommy wallets for men",
"wallets women",
"buffway slim wallet",
"super slim wallet",
"carteras de hombre",
"travando wallets for men",
"wallets for men tommy hilfiger",
"wallet womens",
"alpine swiss wallets for men",
"nautica wallets for men",
"rfid blocking",
"fossil mens wallet",
"mens trifold leather wallet",
"tarjeteros de hombres",
"wallet inserts for credit cards",
"billetera para hombre",
"mens designer wallets",
"men wallet slim",
"men slim wallet",
"herschel wallet men",
"mens bifold wallets",
"wallet rfid",
"rigid wallet",
"mens card wallets",
"levis wallet for men",
"slimfold wallet",
"men purse",
"man wallets",
"billeteras",
"women wallet small",
"gucci card holder",
"titanium wallets for men",
"wallet for men leather",
"ceiling",
"ceiling fan",
"ceiling fans with lights",
"outdoor fan",
"outdoor ceiling fan",
"light fixtures",
"outdoor fans for patios",
"ceiling light",
"kitchen light fixtures",
"ceiling fan with remote",
"outdoor ceiling fan with light",
"ceiling fans",
"outdoor fans for patios waterproof",
"ceiling lights",
"led ceiling light",
"outdoor fans",
"light fixture",
"ceiling fan with lights",
"hunter ceiling fan",
"ceiling fan light covers",
"ceiling fan with light",
"celing fans with light",
"ceiling tiles",
"light fixtures ceiling flush mount",
"outdoor ceiling fans for patios waterproof",
"smart ceiling fan",
"farmhouse ceiling fan",
"smart fan",
"black ceiling fan",
"low profile ceiling fan",
"plug in ceiling fan",
"ceiling fan light kit",
"modern ceiling fan",
"lighting fixtures ceiling",
"patio fan",
"small ceiling fan with light",
"white ceiling fan with light",
"industrial ceiling fan",
"kitchen light",
"white ceiling fan",
"outdoor ceiling fans",
"flush mount ceiling fan",
"flush mount ceiling fan with light",
"hallway light fixtures ceiling",
"garage ceiling fan",
"ceiling fans with lights and remote",
"ceiling light fixture flush mount",
"bedroom light fixtures ceiling",
"lights without wiring",
"wireless ceiling light",
"bedroom ceiling lights",
"rustic ceiling fan",
"small ceiling fan",
"lamparas de techo",
"light fixtures ceiling mount",
"harbor breeze ceiling fan",
"white fan",
"modern light fixture",
"outdoor ceiling fans for patios",
"outdoor ceiling light",
"ceiling lights for bedroom",
"hunter fan",
"outside fan",
"led ceiling lights",
"ceiling fan remote",
"led flush mount ceiling light",
"ceiling fan blades",
"black ceiling fan with light",
"kitchen light fixtures ceiling",
"drop ceiling tiles",
"bedroom ceiling fan",
"hampton bay ceiling fan",
"led ceiling lights flush mount",
"hunter ceiling fans with lights",
"ceiling fan with light and remote",
"patio fan outdoor",
"hunter fan remote",
"ventilador de techo",
"led light fixtures ceiling mount",
"led light fixture",
"low profile ceiling fan with light",
"big asss ceiling fan",
"ceiling lights flush mount",
"ceiling fan no light",
"ceiling led lights",
"enclosed ceiling fan",
"black fan",
"large ceiling fan",
"flush mount light",
"kids ceiling fan",
"portable ceiling fan",
"celing fan",
"ceiling fan light",
"harbor breeze ceiling fan globes",
"led ceiling fan",
"ceiling tile",
"kitchen ceiling light",
"outside fans for patio waterproof",
"hunter ceiling fan remote",
"bedroom light fixture",
"ceiling fan remote control",
"ceiling fan outdoor",
"alexa ceiling fan",
"ceiling fan with remote control and light",
"abanicos de techo",
"outdoor ceiling fan with remote",
"alexa fan",
"led kitchen ceiling light",
"outdoor ceiling fan without light",
"honeywell ceiling fan",
"ceiling fan white",
"fan blades",
"outdoor fan with light",
"fan light",
"overhead light",
"outdoor patio fan",
"ceiling mount light fixture",
"ceiling fan without light",
"harbor breeze",
"ceiling fan light switch",
"ceiling fan light fixture",
"ceiling tiles 24x24",
"porch fan",
"cieling fan",
"modern ceiling fan with light",
"modern fan",
"12v ceiling fan",
"canopy fan",
"harbor breeze fan parts",
"kitchen lights ceiling",
"rv ceiling fan",
"hunter fan light kit",
"remote control ceiling fan",
"52 inch ceiling fan with light",
"ceiling lighting",
"light kit for ceiling fan",
"ceiling fan for bedroom",
"outside ceiling fan",
"hunter fans",
"kitchen ceiling fan",
"battery operated ceiling fan",
"kitchen light fixture",
"bedroom ceiling fans with lights",
"bedroom ceiling light",
"ceiling fan with remote control",
"ceiling light fixtures",
"72 inch ceiling fan",
"hunter outdoor ceiling fan",
"hunter ceiling fan light kit",
"tin ceiling tiles",
"big ass fans",
"flush ceiling fan",
"ceiling fan low profile",
"ceiling fans with remote",
"fan light kit",
"ceiling fan box",
"indoor ceiling fan",
"remote control ceiling fan with light",
"kitchen lighting fixtures ceiling",
"patio ceiling fan",
"ceiling panels",
"smart ceiling light",
"flush mount led lights",
"52 ceiling fan with light",
"rustic ceiling fan with light",
"wifi ceiling fan",
"ceiling fans without lights",
"harbor breeze ceiling fan light kit",
"light fixtures ceiling",
"celing fans with light and remote control",
"ceiling fans with lights flush mount",
"low profile led ceiling light",
"celling fans with lights",
"outdoor ceiling fan with light and remote",
"led ceiling light fixtures",
"flush mount led",
"white ceiling fan with light and remote",
"mini ceiling fan",
"ceiling fan blade covers",
"remote light",
"westinghouse ceiling fan",
"30 inch ceiling fan",
"lights for kitchen",
"hugger ceiling fan with light",
"ceiling fans for bedroom",
"ceiling fan bracket",
"3 blade ceiling fan",
"hugger ceiling fan",
"60 inch ceiling fan",
"metal ceiling fan",
"flush mount",
"ceiling fan black",
"ceiling fan modern",
"exterior ceiling fan",
"42 inch ceiling fan with light",
"drop ceiling",
"kensgrove 72 inch ceiling fan",
"celing fans",
"ceiling fan with lights and remote",
"led fixture",
"outdoor ceiling fans with lights",
"outside fans",
"ceiling fan mounting bracket kit",
"contemporary ceiling fan",
"outdoor gazebo fan",
"ceiling light led",
"hampton bay ceiling fan light switch parts",
"white ceiling light",
"tropical ceiling fan",
"outdoor ceiling fan with light for patios",
"shop ceiling fan",
"52 inch ceiling fan",
"vintage ceiling fan",
"low profile flush mount ceiling fan",
"light mount",
"black outdoor ceiling fan",
"hampton bay ceiling fan light kit",
"12 volt ceiling fan",
"ceiling fan alexa",
"large outdoor fan",
"ceiling tiles glue up",
"outside fans for patio",
"ceiling fan flush mount",
"ceiling fan with bright light",
"solar ceiling fan",
"72 ceiling fan",
"hunter dempsey 52 inch ceiling fan with light",
"fan ceiling",
"led lights for kitchen",
"flush mount lighting",
"42 inch ceiling fan",
"outdoor ceiling fan blades",
"hunter ceiling fans",
"honeywell fan remote",
"ceiling fan balancing kit",
"big asss ceiling fan outdoor",
"porch ceiling fan",
"hunter ceiling fan with remote",
"hunter ceiling fan remote control",
"small outdoor fan",
"gold ceiling fan",
"farmhouse fan",
"metal ceiling tiles",
"small room ceiling fan",
"wood ceiling fan",
"ceiling fan led",
"home decorators collection ceiling fan",
"wifi fan",
"enclosed ceiling fan with light",
"sealing fan",
"ceiling fan 52 inch with light",
"pen",
"pens",
"gel pens",
"fountain pen",
"sharpie pens",
"pens fine point",
"muji pens",
"parker pen",
"g2 pens",
"ink pens",
"pens medium point",
"black pens",
"ballpoint pens",
"pilot pens",
"gel pen",
"pilot g2 pens",
"pen set",
"japanese pens",
"ink pen",
"pens for journaling no bleed",
"fine point pen",
"pens bulk",
"writing pens",
"fountain pens",
"pens for women",
"edc pen",
"bulk pens",
"pilot",
"bolt action pen",
"black pen",
"cool pens",
"ballpoint pen",
"fancy pens",
"fine point pens",
"fancy pen",
"le pen",
"rollerball pen",
"black gel pens",
"ball point pens",
"muji pens 0.38",
"pens for note taking",
"pilot pen",
"pentel rsvp fine point pen",
"luxury pen",
"drawing pen",
"ballpoint pens black",
"fine tip pens",
"stationary pens",
"pens and pencils",
"gel ink pens",
"metal pen",
"retractable pens",
"bic pen",
"tactical pens",
"office pens",
"black ink pens",
"pen ink",
"nice pens",
"japanese pen",
"ball point pen",
"rollerball pens",
"waterman pen",
"note taking pens",
"nice pen",
"ink joys pens",
"gel pens black",
"extra fine point pens",
"paper mate pens",
"sharpie gel pen",
"muji pens 0.5",
"click pens",
"personalized pen",
"no bleed pens",
"best pens",
"rite in the rain pen",
"art pen",
"ball pen",
"pens for journaling",
"ink pens black",
"writing pen",
"black ink pen",
"erasable pens black",
"bullet pen",
"luxury pens",
"bullet journal pen",
"fine tip pen",
"cool pen",
"amazon basics pens",
"pens medium point black ink",
"retractable pen",
"lapiceros",
"ink pens medium point",
"korean pens",
"engraved pen",
"custom pen",
"executive pen",
"journaling pen",
"brass pen",
"ultra fine point pens",
"pens for men",
"sharpie s gel",
"0.38mm pen",
"silver pen",
"0.5 pens",
"cheap pens",
"pens for women journaling",
"gel pens medium point",
"fine pens",
"gel pens fine point",
"fisher pen",
"metal pens",
"journal pen",
"engraved pens personalized",
"amazon pens",
"expensive pens",
"gel pens papermate",
"nice pens for men",
"writing pens for journaling",
"pack of pens",
"black pens fine point",
"pen sets for men gift",
"pens black",
"micro pens",
"pilot ink",
"black gel pen",
"box of pens",
"papermate pen",
"pen pack",
"gell pens",
"best pen",
"sharpie gel pens",
"small pen",
"polar pen",
"fine point gel pens",
"boligrafos",
"unique pens",
"dad pen",
"papermate ballpoint pens",
"black pens medium point",
"journal pens no bleed through",
"pens under 5 dollars",
"inkjoy gel pens 0.5",
"refillable pen",
"pens for school",
"gift pen",
"ink pens fine point black",
"luxury pens for men",
"waterman pens",
"zebra pens fine point",
"best pens for writing",
"small pens",
"ballpoint pens fine point",
"ball pens",
"fountain pen set",
"zebra z grip medium pens",
"good pens",
"bic round stic",
"all weather pen",
"military pen",
"fine pen",
"fountain pen converter",
"sharpie gel",
"plumas para escribir",
"thin pens",
"lapiceros personalizados",
"piolet g2 pen 07",
"tatical pen",
"pen sets for women",
"carbon fiber pen",
"gel pena",
"office pen",
"professional pen",
"black ballpoint pen",
"lepen",
"uzi tactical pen",
"red pens fine point",
"papermate black pens",
"grafton pen",
"server pens",
"ink pens for journaling",
"pen fine point",
"pen sets",
"police pen",
"refillable pens",
"pilot fine point pens",
"pen gift",
"business pens",
"bolt pen",
"weighted pen",
"fine point ballpoint pens",
"pens pilot",
"smooth writing pens",
"bic fine point pens",
"ballpen",
"colored gel pen",
"steel pen",
"planner pen",
"chrome pen",
"ink gel pens",
"pilot pens fine point black",
"professional pens",
"pluma",
"ink for fountain pens",
"silver pens",
"parker rollerball pen",
"pen gel",
"ball point journal pens",
"sharpie pen fine",
"needle tip pens",
"gel ink pen",
"pen pilot",
"edc pens",
"fine point colored pens",
"0.3 pen",
"ooly pens",
"nib pen",
"skilcraft pen",
"pens ballpoint",
"sharpies gel pens 0.7",
"take note pens",
"pens black ink",
"cool pens for men",
"black art pens",
"refillable fountain pen",
"hongdian fountain pen",
"0.38 pens",
"executive pens for men",
"black ballpoint pens",
"think ink pen",
"smooth pens",
"ink pens for writing",
"pilot better retractable fine point pen",
"high quality pens",
"black pens bulk",
"retractable ballpoint pens",
"roller ball pen",
"smooth pen",
"ultra fine pen",
"click pen",
"pen and ink",
"extra fine fountain pen",
"glass pens and ink",
"cross pen refills black fine point",
"jel pens",
"pen nibs",
"le pens",
"office supplies pens",
"gun",
"massage gun",
"bb gun",
"airsoft guns",
"gun safe",
"massage gun deep tissue",
"pellet gun",
"massage",
"airsoft",
"guns",
"airsoft pistols",
"theragun",
"bb guns for adults",
"bb gun pistol",
"gun safes for pistols",
"hypervolt massage gun",
"bb guns",
"gun cabinet",
"airsoft gun",
"percussion massager gun",
"percussion massage gun",
"hypervolt",
"air softgun gun",
"air gun",
"muscle massage gun",
"pellet gun pistol",
"pistol",
"glock bb gun",
"massagers handheld deep tissue",
"pistol safe",
"handgun safe",
"gun cases for pistols",
"co2 pistol",
"airsoft pistol",
"bb",
"massager gun",
"bbs for bb guns",
"small safe",
"muscle massager",
"biometric gun safe",
"bb gun rifle",
"percussion massager",
"gun safes",
"deep tissue massager",
"air pistol",
"daisy bb gun",
"pellet gun rifle",
"bb pistol",
"pellet guns",
"deep tissue massage gun",
"deep tissue percussion muscle massager",
"pellet pistol",
"fake gun",
"umarex",
"co2 bb gun",
"gun magnet",
"muscle gun",
"message gun",
"real guns that shoot real bullets",
"hyperice",
"gun cleaning",
"airsoft pistols co2",
"muscle gun massager",
"paintball gun pistol",
"glock 19 bb gun",
"fingerprint gun safe",
"co2 cartridges 12g",
"prop gun",
"theragun g3pro",
"airsoft glock",
"hand gun",
"deep muscle massager",
"gun lock",
"bb rifle",
"massage guns",
"co2 airsoft pistols",
"massager gun deep tissue",
"gun lock box",
"bb guns for kids",
"bebe guns for adults",
"full auto bb guns",
"massage gun for athletes",
"magnetic gun mount",
"biometric safe",
"air gun pistol",
"hyperice hypervolt",
"muscle massager gun",
"handgun",
"pistolas de balines",
"gun massager",
"deep tissue massager handheld",
"gun locker",
"biometric gun safe for handgun",
"rubber bullet gun",
"airsoft guns pistol",
"fingerprint safe",
"car gun safe",
"small lock box",
"blowback bb gun",
"deep muscle massager gun",
"handgun safes for pistols",
"9mm gun",
"bb gun ammo",
"deep tissue massage",
"fake guns",
"airgun",
"revolver bb gun",
"gun storage",
"ballistol gun cleaner",
"gun magnet for vehicle",
"real gun",
"glock airsoft pistol",
"pellet guns for adults",
"gun box",
"gun vault",
"pistolas",
"car gun holster mount",
"metal bb gun",
"gun accessories for men",
"airsoft guns co2",
"bb gun pistol co2",
"pistols",
"real guns",
"hand guns",
"bb gun revolver",
"9mm pistol",
"rifle safes for home",
"co2 gun",
"pistola",
"gun magnets for home",
"glock 17 bb gun",
"177 bbs",
"small gun safe",
"automatic bb gun",
"air soft gun",
"hypervolt plus",
"co2 rifle",
"co2 bb gun pistol",
"air softgun gun pistol",
"bb gun sniper",
"crossman pellet gun",
"air soft guns",
"airsoft ammo",
"car safe",
"blowback airsoft pistols",
"brookstone massager",
"bb gun co2",
"hypervolt plus massage gun",
"massage deep tissue",
"air guns",
"bbgun",
"co2 airsoft guns",
"bb revolver",
"blank gun",
"pistol safe quick access",
"bedside gun safe",
"bb gun glock",
"gun lights for pistols",
"massage gun quiet",
"deep tissue massage gun for athletes",
"2a4life",
"hand gun safe",
"co2 pellet gun",
"airsoft guns automatic",
"rifle gun safe",
"speed gun",
"muscle massage",
"pistola de balines de metal",
"co2 cartridges bb gun",
"long gun safe",
"gun holder",
"22 pistol",
"vulcan quickdraw gun mount",
"gun holster for vehicle",
"cheap airsoft guns",
"full auto airsoft guns",
"magnetic gun mount for vehicle",
"prop guns",
"gun lock boxes for pistols",
"percussive massage gun",
"airsoft glock 19",
"automatic airsoft gun",
"pistol gun",
"bebe gun",
"gun safes for home rifle and pistols",
"drawer safe",
"airsoft pellets",
"wall safes",
"gun safe biometric",
"beebee gun",
"airsoft co2 pistols",
"firearms",
"bb shotgun",
"bbguns guns pistol",
"1911 bb gun",
"22 pellet gun",
"airsoft bb",
"masage gun",
"real guns pistol for adults",
"electric airsoft pistols",
"bb guns for adults automatic",
"hypervolt massager",
"pistol lock box",
"glock airsoft",
"gun safe for pistols",
"head massage",
"umarex glock 17 gen 4",
"4.5 mm bbs",
"bb pellets",
"gun magnets",
"22 gun",
"small gun safe for handguns",
"gun safe for cars",
"c02 cartridges for bb gun",
"co2 guns",
"shotguns for sale",
"paintball handgun",
"gun massager for muscle",
"replica gun",
"quick access handgun safe",
"bb rifles for adults",
"bb pistols co2",
"fingerprint gun safe for handgun",
"airsoft pistols co2 blowback",
"massage gun deep tissue percussion muscle massager",
"portable gun safe",
"biometric handgun safe",
"bb gun scope",
"airsoft machine gun",
"semi auto airsoft pistol",
"under bed gun safe",
"sig sauer pellet gun",
"stop box",
"glock 19 airsoft",
"prop guns for movies that look real",
"rubber bullets",
"massaging gun",
"gun magnet mount",
"bibi guns for adults",
"guns for adults",
"bb gun pistol glock",
"gun vault pistol safe",
"rubber bullet gun self defense",
"hand guns for men",
"snap safe lock box",
"air pistols co2 powered automatic",
"airsoft co2",
"vehicle gun safe",
"shirt",
"shirts for men",
"mens shirts",
"tshirts for mens",
"shirts",
"big and tall shirts for men",
"t shirts",
"men shirts",
"tshirts",
"mens shirt",
"tee shirts mens",
"mens shirts clearance",
"mens shirts short sleeve casual",
"men shirt",
"work shirts for men",
"plain t shirts for men",
"men t shirt",
"polo shirt",
"big and tall t shirts for men",
"woman shirts",
"womens shirt",
"men shirts clearance",
"shirt for men",
"women shirt",
"tshirts for men",
"mens big and tall t shirts",
"plain t shirts",
"tee shirts",
"men t shirts",
"shirt for women",
"mens big and tall shirts",
"t shirts men",
"camisa para hombre",
"bulk tshirts",
"tees for men",
"mens plain t shirts",
"tee shirt",
"shirts for women clearance",
"shirts men",
"a shirts for men",
"mens a shirts",
"shirt men",
"plain shirts",
"a shirts",
"pack of shirts for men",
"pack of shirts",
"mens tall shirts",
"man shirts",
"shirts for men pack",
"big and tall shirts",
"camisas de trabajo para hombre",
"t shirt for men pack",
"bulk shirts",
"men tee shirt",
"plain tshirts",
"camisa",
"men t shirts pack",
"tall shirts for men",
"mens shirts pack",
"shirt pack",
"a shirt",
"camisas para hombre",
"mens t shirts clearance",
"cheap shirts for women",
"cheap shirts for men",
"camisa de hombre",
"plain shirts for men",
"polo shirt men",
"cheap shirts",
"mens shirts big and tall",
"big and tall mens shirts",
"pack of tshirts",
"plain tshirts for men",
"big mens shirts",
"man shirt",
"pack of shirts for women",
"tshirt pack men",
"big and tall tshirts for men",
"shirt packs for men",
"mens shirt pack",
"men big and tall t shirts",
"mens a shirt",
"shirts for men big and tall",
"tahirts",
"plain shirt",
"camisetas polo para hombre",
"teeshirts mens",
"mens tee shirt",
"lightweight shirts for men",
"pack of tshirts for men",
"athletic shirts men",
"men shirt pack",
"shirts mens",
"camisas hombre",
"bulk shirt",
"remeras hombre",
"men s shirts",
"big and tall tee shirts for men",
"t shirts bulk",
"men tee shirts clearance",
"tshirts pack",
"tall mens shirts",
"large shirts for men",
"mens tall polo shirts",
"plain mens tshirts",
"man tshirt",
"tshirt mens",
"playera para hombre",
"shirts for mens",
"ashirts for men",
"mens tall tee shirts",
"mens medium shirts",
"mens tee shirts clearance",
"soft tee shirts men",
"plain t shirts for men pack",
"big and tall shirt",
"a tee shirts for men",
"large tall shirts for men",
"tshirt bulk",
"big & tall shirts for men",
"cheap shirt",
"men s tee shirts",
"mens large shirts",
"men big and tall shirts",
"big and tall suits for men",
"thin t shirts for men",
"men pack of tshirts",
"shirt packs for women",
"men tee shirts",
"tall shirts",
"plain t shirt for men",
"tall womens shirts",
"t shirt bulk",
"xl mens shirts",
"shirt packs",
"shirt mens",
"lightweight tshirts for men",
"big shirts for men",
"mens ahirts",
"shirt man",
"ashirts",
"mems shirts",
"tall size t shirts for men",
"playeras polo",
"shrit",
"tall shirt",
"mens small shirts",
"brand shirts for men",
"mens shitts",
"large shirts",
"shirts big and tall",
"mens big and tall a shirts",
"a shirt big and tall",
"polo big and tall",
"men shirts clearance polo",
"big size t shirts for men",
"mens large polo shirts",
"ahirt",
"shiet",
"shirt bulk",
"thick shirt",
"large tall shirt",
"large shirt",
"plain shirt pack",
"big shirt",
"medium shirt",
"lightweight shirt",
"shirt for men pack",
"men s shirt",
"mens tall shirt",
"mens shir",
"mans shirt",
"mens shitt",
"shirt pack for men",
"large mens shirt",
"mens large shirt",
"mens small shirt",
"mens shirt medium",
"tall mens shirt",
"la shirt",
"bi shirt",
"shirt for man",
"lerage shirts",
"medium shirts",
"large mens shirts",
"shirt shirt",
"shirys",
"pack shirts",
"men large shirts",
"big man shirts",
"big little shirt",
"shirts pack",
"mens shirts large",
"plain shirt for men",
"shrits",
"large men shirts",
"medium mens shirts",
"lightweight mens shirt",
"ahirts",
"men shitrs",
"shirt for big men",
"mens lightweight shirts",
"bulk of shirts",
"clearance shirts",
"medium tall mens shirts",
"shirts plain",
"shirts clearance",
"shirts cheap",
"menshirts",
"mens large shirts clearance",
"small mens shirts",
"large tall shirts",
"mens shirts medium",
"mens cheap shirts",
"men pack of shirts",
"shirts for large men",
"mens size large shirts",
"big shirts",
"cheap men shirts",
"shirt pack men",
"shirts for mem",
"ahirts for men",
"plain shirts for men pack",
"mens shirts tall",
"men small shirts",
"mens shirts size large",
"mens plain shirts",
"thin shirts for men",
"big and tall men shirts",
"brand shirts",
"boomerang",
"boomerang for kids",
"boomerang for adults",
"aerobie pro",
"boomarang outdoor toy",
"boomerangs",
"boomarang",
"bommerangs",
"left handed boomerang",
"nerf boomerang",
"channel craft",
"boomerang ball",
"kids boomerang",
"boomerang surfer",
"voisons boomerang",
"bomerang",
"boomerang tiger blue",
"chuckit boomerang",
"mega bowmerang tiger",
"boomeran",
"boomerangg",
"professional boomerang",
"boomerang professional",
"bumerang for kids",
"boomerang real",
"boomerangs for kids",
"boomerang kids",
"bomerange",
"boomarangs for kids",
"boomrangs",
"real boomerang",
"boomerang cyclotrac",
"returning boomerang",
"colorado boomerang",
"australian boomerang"]

SCRAPE_WORKERS = int(os.getenv('SCRAPE_WORKERS', 50))
DEBUG = eval(os.getenv('DEBUG', 'False'))

sites_sheet = GoogleSheets('Sites & products')
atlas = MongoAtlas()

app = Flask(__name__)
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0


def log_except_hook(*exc_info):
    text = "".join(traceback.format_exception(*exc_info))
    logging.error("Unhandled exception: %s", text)


def start_scrape(function, items, processors):
    with ThreadPoolExecutor(max_workers=processors) as executor:
        for item in items:
            try:
                executor.submit(function, item)
            except Exception as e:
                print(f"Error to  {function.__name__} with {e} item {item}")


def load_data(link):
    with futures.ThreadPoolExecutor(max_workers=3) as executor:
        tasks = [executor.submit(get_rank, link),
                 executor.submit(get_store_products, link),
                 executor.submit(get_facebook_data, link)]

        futures.wait(tasks, timeout=70000, return_when=futures.ALL_COMPLETED)
        return tasks[0].result(), tasks[1].result(), tasks[2].result()


def key_words_test(key_words, hours_in_trend, max_workers):
    tasks = []
    with futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        for key_word in key_words:
            tasks.append(executor.submit(lambda p: GoogleTrendsApi().search_trend_by_keyword(*p), [[key_word], hours_in_trend]))
    futures.wait(tasks, return_when=futures.ALL_COMPLETED)
    return list(map(lambda a: a.result(), tasks))


def update_facebook_data(site_link):
    try:
        facebook_ads = get_facebook_data(site_link)
        if 'ok' in facebook_ads['facebook'] and facebook_ads['facebook']['ok']:
            print(f"Finish update_facebook_data site {site_link}")
        else:
            print(f"Cant add ads to  {site_link}")
        atlas.add_facebook_ads(site_link, facebook_ads)
    except Exception as e:
        pass


def get_site_data(site):
    try:
        stats, products, facebook_ads = load_data(site.link)
        site.add_stats(stats)
        site.set_products_lean(products)
        site.add_ads(facebook_ads)

        atlas.update_site(site)
    except Exception as e:
        print(f"Error to  {site.link} with {e}")


def start_update(function, processors):
    sites_to_update = atlas.get_data(function, sites_sheet.get_sites())
    random.shuffle(sites_to_update)
    if len(sites_to_update):
        start_scrape(function, sites_to_update, processors)
    else:
        print(f"No more sites to {function}")


def test_facebook_data(site_link):
    facebook_data = get_facebook_data(site_link)
    if facebook_data:
        print(f"Finish {site_link} with facebook data")
    else:
        print(f"Finish {site_link} with no facebook data")


def test_facebook_ads(page_id):
    facebook_ads = get_ads_data_test(page_id)
    if facebook_ads:
        print(f"Finish {page_id} with facebook ads")
    else:
        print(f"Finish {page_id} with no facebook ads")


def test_site_data(link):
    site = sites_sheet.get_site_by_link(link)
    if site:
        get_site_data(site)


def print_loading_data():
    print("Number of cpu : ", multiprocessing.cpu_count())


@app.route("/evaluate", methods=['GET', 'POST'])
def evaluate():
    if request.method == 'POST':
        data = request.form.to_dict(flat=False)
        if data:
            evaluate_site(data['data_link'][0],
                          eval(data['is_dropshipper'][0]),
                          data['main_product'][0],
                          eval(data['is_branded_products'][0]),
                          int(data['our_ranking'][0]))
    return open_site(get_site_to_evaluate())


@app.route("/start_update", methods=['GET', 'POST'])
def update_all():
    global main_thread
    function = request.args.get('update')
    processors = int(request.args.get('processors'))
    print('Received function API at process: ' + function)

    if not function:
        return "Missing data"

    data = {'processors': processors, 'function': get_site_data}
    if function == "facebook":
        data['function'] = update_facebook_data

    main_thread = Thread(target=start_update, kwargs=data)
    main_thread.start()

    # Immediately return a 200 response to the caller
    return "Started process"


@app.route("/start_msips_scrapper", methods=['GET'])
def start_msips_scrapper():
    global main_thread
    start_page = request.args.get('start_page')
    number_of_pages = int(request.args.get('number_of_pages'))
    attempts = int(request.args.get('attempts'))
    print('Received function API at process: start_msips_scrapper')

    data = {'start_page': start_page,
            'number_of_pages': number_of_pages,
            'attempts': attempts}

    main_thread = Thread(target=get_myips_link, kwargs=data)
    main_thread.start()

    # Immediately return a 200 response to the caller
    return "Started start_msips_scrapper process"


@app.route("/get_key_word_trend", methods=['POST'])
def get_key_word_trend():
    key_words = request.form.getlist('key_words')
    hours_in_trend = int(request.form.get('hours_in_trend'))
    max_workers = int(request.form.get('max_workers'))

    return jsonify(get_trend(key_words, hours_in_trend, max_workers))


@app.route("/save_ips", methods=['POST'])
def save_ips():
    sites = request.json
    with ThreadPoolExecutor(max_workers=50) as executor:
        for site_data in sites:
            try:
                site = Site(ranking=site_data['ranking'],
                            link=site_data['link'],
                            daily_visitors=site_data['daily_visitors'],
                            monthly_visitors=site_data['monthly_visitors'])
                executor.submit(add_site, site)
            except Exception as e:
                print(f"Error to save_ips with {e} site_link {site_data['link']}")
    return "Saved save_ips"


if __name__ == '__main__':
    # app.run(debug=DEBUG)
    # sys.excepthook = log_except_hook
    # print_loading_data()

    # data = key_words_test('World Cup', 8, 20)
    # for key in words:
    #     data = search_trend_by_keyword([key], 38)
    #     print(data)
    newwords = words[:]
    shuffle(newwords)
    data = key_words_test(newwords, 38, 100)

    # data = google_trends_api.search_trend_by_keyword(['luxury pen'], 38, debug=True)

    # run_test(100)
    # get_interest_over_time(['World Cup'], 160)
    # test_facebook_data('bodymattersgold.com')
    # test_site_data('bodymattersgold.com')

    # test_facebook_ads('323363524483195')
